DROP TABLE IF EXISTS EMPLOYEES;

CREATE TABLE EMPLOYEES (
  ID INT AUTO_INCREMENT  PRIMARY KEY,
  EMPLOYEE_ID VARCHAR(250) NOT NULL,
  FIRST_NAME VARCHAR(250) NOT NULL,
  LAST_NAME VARCHAR(250) NOT NULL,
  EMAIL VARCHAR(250) DEFAULT NULL,
  DATE_OF_JOINING DATE,
  SALARY VARCHAR(250)
);

CREATE TABLE EMP_MOBILE_NUMBERS (
    ID INT AUTO_INCREMENT  PRIMARY KEY,
    EMP_ID INT,
    MOBILE_NUMBER VARCHAR(250),
    FOREIGN KEY ( EMP_ID ) REFERENCES EMPLOYEES ( ID )
)